CREATE DATABASE IF NOT EXISTS suzhida CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'suzhida'@'%' IDENTIFIED BY 'suzhida';
GRANT ALL PRIVILEGES ON suzhida.* TO 'suzhida'@'%';
FLUSH PRIVILEGES;
